name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.3.1
homepage: https://github.com/fluttercommunity/chewie

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  cupertino_icons: 
  flutter:
    sdk: flutter
  provider:
  video_player:
  wakelock: 
  very_good_analysis: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  uses-material-design: true
